version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-app-game-kanak2:latest
    container_name: baca-ceria
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
